[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SH110X @ ^2.1.10